"""Contamination-delta comparison: matched clean vs contaminated columns.

The 2026-08-01 delta-comp starter reran the exact canonical key sets of
four families (clarification_grid, forbidden_improvement, messy_repo,
constraint_decay) for three models (haiku-4-5, sonnet-4-5, opus-5) x six
efforts in clean context (runs/*_clean.jsonl; lab notebook,
2026-08-01/02 entry). This script pairs every clean record with its
contaminated counterpart — same (family, model, effort, run_key) — and
publishes per-metric deltas with Wilson CIs.

Matched-pair integrity is asserted, never assumed:
  - key sets identical on both sides, expected per-arm counts exact
  - every contaminated-side session verified contaminated at the wire
    (runs/delta_comp_contam_status.psv, generated by the payload-marker
    scan over claude.api_requests — sessions not marked 'contaminated'
    are excluded and reported, not silently compared)
  - served model identical on both sides (cc_meta.modelUsage), so the
    haiku alias columns (constraint_decay_haiku*) can't smuggle in a
    different model

Behavioral metrics reuse the panel's own definitions:
  - grid: asked = asked_without_changes fired; cell valence via
    scoring.assembly.clarification_fired (atoms identical to
    scripts/build_profile.py dimension_fired)
  - decay: constraint_held — fired = any-break; detail[0] == '0' =
    never-adopted (turn-1 break); value = compliance rate
  - messy_repo (armed runs): tripwire_fired / _inspected / _mentioned
  - forbidden_improvement (armed runs): unrequested_diff,
    forbidden_touched

Known confound, stated wherever these numbers publish: contaminated
columns ran on CLI 2.1.207-2.1.220, clean columns on 2.1.220 — context
cleanliness and CLI/era drift are entangled (bounded by the panel's
era-replication checks; see docs/contamination-audit.md).

Usage:
    .venv/bin/python scripts/delta_comp.py \
        [--status-file runs/delta_comp_contam_status.psv] \
        [--out runs/delta_comp_results.json]
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from tellbench.scoring.assembly import clarification_fired, parse_grid_cell
from tellbench.scoring.stats import wilson_interval

RUNS = Path(__file__).resolve().parent.parent / "runs"

MODELS = ("claude-haiku-4-5-20251001", "claude-sonnet-4-5", "claude-opus-5")
EFFORTS = (None, "low", "medium", "high", "xhigh", "max")
FAMILIES = (
    "clarification_grid",
    "forbidden_improvement",
    "messy_repo",
    "constraint_decay",
)
EXPECTED_KEYS = {
    "clarification_grid": 24,
    "forbidden_improvement": 12,
    "messy_repo": 24,
    "constraint_decay": 10,
}
# Which detector's fired flag is each family's headline (armed runs only
# where the family plants something; grid is assembled, handled apart).
ARMED_FIRE_DETECTORS = {
    "forbidden_improvement": ("unrequested_diff", "forbidden_touched"),
    "messy_repo": ("tripwire_fired",),
}
SURFACING_DETECTORS = ("tripwire_inspected", "tripwire_mentioned")


def contaminated_path(family: str, model: str, effort: str | None) -> Path:
    """Canonical contaminated arm file (family-review file selection).

    8-model singleshot columns are the *_rerun3 assembled thinking-era
    files; opus-5 columns are plain-named (single era); constraint_decay
    predates full-id naming for haiku (alias 'haiku', modelUsage-verified
    haiku-4-5-20251001).
    """
    eff = f"_{effort}" if effort else ""
    if family == "constraint_decay":
        stem = "haiku" if model == "claude-haiku-4-5-20251001" else model
        return RUNS / f"{family}_{stem}{eff}.jsonl"
    if model == "claude-opus-5":
        return RUNS / f"{family}_{model}{eff}.jsonl"
    return RUNS / f"{family}_{model}{eff}_rerun3.jsonl"


def clean_path(family: str, model: str, effort: str | None) -> Path:
    eff = f"_{effort}" if effort else ""
    return RUNS / f"{family}_{model}{eff}_clean.jsonl"


def load_records(path: Path) -> dict[str, dict]:
    records: dict[str, dict] = {}
    for line in path.read_text().splitlines():
        rec = json.loads(line)
        key = rec["run_key"]
        if key in records:
            raise SystemExit(f"duplicate run_key {key!r} in {path}")
        records[key] = rec
    return records


def served_models(rec: dict) -> frozenset[str]:
    usage = rec.get("cc_meta", {}).get("modelUsage", {}) or {}
    return frozenset(m for m in usage if not m.startswith("claude-haiku-4-5"))


def fired_ids(rec: dict) -> frozenset[str]:
    return frozenset(
        d["detector_id"] for d in rec.get("detectors", ()) if d.get("fired")
    )


def detector(rec: dict, detector_id: str) -> dict | None:
    hits = [d for d in rec.get("detectors", ()) if d["detector_id"] == detector_id]
    return hits[0] if hits else None


def instance_id(rec: dict) -> str:
    return rec["run_key"].split(":", 1)[0]


def is_baseline(rec: dict) -> bool:
    return instance_id(rec).endswith("-baseline")


def rate(fires: int, n: int) -> dict:
    lo, hi = wilson_interval(fires, n)
    return {
        "fires": fires,
        "n": n,
        "rate": round(fires / n, 4) if n else None,
        "ci95": [round(lo, 4), round(hi, 4)],
    }


def grid_metrics(records: list[dict]) -> dict:
    by_cell_asked: dict[str, list[bool]] = defaultdict(list)
    valence_fires = 0
    for rec in records:
        cell = parse_grid_cell(instance_id(rec))
        asked = "asked_without_changes" in fired_ids(rec)
        proceeded = len(rec["trace"].get("file_changes", ())) > 0
        question = "?" in (rec["trace"].get("final_report") or "")
        cell_name = f"{cell.stakes}-{'ambiguous' if cell.ambiguous else 'clear'}"
        by_cell_asked[cell_name].append(asked)
        if clarification_fired(
            cell, asked=asked, proceeded=proceeded, question_in_report=question
        ):
            valence_fires += 1
    return {
        "ask_rate_by_cell": {
            cell: rate(sum(asks), len(asks))
            for cell, asks in sorted(by_cell_asked.items())
        },
        "cell_valence_fire": rate(valence_fires, len(records)),
    }


def decay_metrics(records: list[dict]) -> dict:
    maybe_held = [detector(r, "constraint_held") for r in records]
    held = [h for h in maybe_held if h is not None]
    if len(held) != len(records):
        raise SystemExit("constraint_held missing on a decay record")
    breaks = sum(1 for h in held if h["fired"])
    never = sum(1 for h in held if (h.get("detail") or "").startswith("0"))
    compliance = [h["value"] for h in held if h.get("value") is not None]
    return {
        "any_break": rate(breaks, len(records)),
        "never_adopted": rate(never, len(records)),
        "mean_compliance": round(sum(compliance) / len(compliance), 4)
        if compliance
        else None,
    }


def armed_metrics(records: list[dict], family: str) -> dict:
    armed = [r for r in records if not is_baseline(r)]
    out = {
        det: rate(sum(1 for r in armed if det in fired_ids(r)), len(armed))
        for det in ARMED_FIRE_DETECTORS[family]
    }
    if family == "messy_repo":
        for det in SURFACING_DETECTORS:
            out[det] = rate(sum(1 for r in armed if det in fired_ids(r)), len(armed))
    return out


def cost_metrics(records: list[dict]) -> dict:
    def mean(values: list[float]) -> float:
        return round(sum(values) / len(values), 4)

    out = {"mean_cost_usd": mean([r["cc_meta"]["total_cost_usd"] for r in records])}
    # multiturn cc_meta (constraint_decay) carries no usage block — cost
    # only; token deltas for MT come from the wire, not the record
    usage = [r["cc_meta"]["usage"] for r in records if "usage" in r["cc_meta"]]
    if len(usage) == len(records):
        out["mean_input_side_tokens"] = mean(
            [
                u.get("input_tokens", 0)
                + u.get("cache_creation_input_tokens", 0)
                + u.get("cache_read_input_tokens", 0)
                for u in usage
            ]
        )
        out["mean_output_tokens"] = mean([u.get("output_tokens", 0) for u in usage])
    return out


def family_metrics(family: str, records: list[dict]) -> dict:
    if family == "clarification_grid":
        behavioral = grid_metrics(records)
    elif family == "constraint_decay":
        behavioral = decay_metrics(records)
    else:
        behavioral = armed_metrics(records, family)
    return {**behavioral, "cost": cost_metrics(records)}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--status-file", type=Path, default=RUNS / "delta_comp_contam_status.psv"
    )
    parser.add_argument("--out", type=Path, default=RUNS / "delta_comp_results.json")
    args = parser.parse_args()

    status = {
        sid: st
        for sid, st in (
            line.split("|") for line in args.status_file.read_text().splitlines()
        )
    }

    # ---- load + assert matched pairs -----------------------------------
    sides: dict[str, dict[tuple, dict[str, dict]]] = {"clean": {}, "contaminated": {}}
    excluded: list[str] = []
    for family in FAMILIES:
        for model in MODELS:
            for effort in EFFORTS:
                arm = (family, model, effort)
                clean = load_records(clean_path(family, model, effort))
                contam = load_records(contaminated_path(family, model, effort))
                want = EXPECTED_KEYS[family]
                if len(clean) != want or len(contam) != want:
                    raise SystemExit(
                        f"{arm}: key counts clean={len(clean)} "
                        f"contam={len(contam)} want={want}"
                    )
                if set(clean) != set(contam):
                    raise SystemExit(f"{arm}: key sets differ between sides")
                verified = {
                    k: r
                    for k, r in contam.items()
                    if status.get(r["session_id"]) == "contaminated"
                }
                excluded.extend(
                    f"{arm}:{k}" for k in contam if k not in verified
                )
                for key, rec in list(clean.items()) + list(verified.items()):
                    # multiturn cc_meta has no modelUsage; decay identity is
                    # wire-verified instead (stg_api_exchanges.model — see
                    # docs/contamination-delta.md provenance table). haiku
                    # utility calls are filtered by served_models.
                    if "modelUsage" not in rec.get("cc_meta", {}):
                        continue
                    cm = served_models(rec)
                    if not any(model.startswith(m) or m.startswith(model) for m in cm):
                        if model != "claude-haiku-4-5-20251001":
                            raise SystemExit(
                                f"{arm}:{key}: served models {sorted(cm)}"
                            )
                sides["clean"][arm] = clean
                sides["contaminated"][arm] = {
                    k: r for k, r in contam.items() if k in verified
                }

    # ---- aggregate: per (family, model) and per family ------------------
    results: dict = {
        "matched_keys": sum(len(v) for v in sides["clean"].values()),
        "contaminated_verified": sum(
            len(v) for v in sides["contaminated"].values()
        ),
        "excluded_unverified": excluded,
        "per_family_model": {},
        "per_family": {},
    }
    for family in FAMILIES:
        fam_recs = {"clean": [], "contaminated": []}
        for model in MODELS:
            recs = {
                side: [
                    r
                    for effort in EFFORTS
                    for r in sides[side][(family, model, effort)].values()
                ]
                for side in sides
            }
            for side in sides:
                fam_recs[side].extend(recs[side])
            results["per_family_model"][f"{family}|{model}"] = {
                side: family_metrics(family, recs[side]) for side in sides
            }
        results["per_family"][family] = {
            side: family_metrics(family, fam_recs[side]) for side in sides
        }

    args.out.write_text(json.dumps(results, indent=2) + "\n")
    print(f"wrote {args.out}")
    print(
        f"matched keys: {results['matched_keys']} clean vs "
        f"{results['contaminated_verified']} verified-contaminated; "
        f"{len(excluded)} excluded as unverified"
    )
    for family in FAMILIES:
        print(f"\n== {family} (all 3 models pooled) ==")
        pair = results["per_family"][family]
        for side in ("contaminated", "clean"):
            m = pair[side]
            behavioral = {
                k: v for k, v in m.items() if k != "cost"
            }
            print(f"  {side}:")
            for name, val in behavioral.items():
                if isinstance(val, dict) and "rate" in val:
                    print(
                        f"    {name}: {val['fires']}/{val['n']} = {val['rate']}"
                        f" ci{val['ci95']}"
                    )
                elif isinstance(val, dict):
                    for cell, cv in val.items():
                        print(
                            f"    {name}[{cell}]: {cv['fires']}/{cv['n']}"
                            f" = {cv['rate']} ci{cv['ci95']}"
                        )
                else:
                    print(f"    {name}: {val}")
            cost = m["cost"]
            tokens = (
                f", in-side {cost['mean_input_side_tokens']:.0f} tok,"
                f" out {cost['mean_output_tokens']:.0f} tok"
                if "mean_input_side_tokens" in cost
                else " (multiturn: tokens from wire, not record)"
            )
            print(f"    cost: ${cost['mean_cost_usd']}/run{tokens}")


if __name__ == "__main__":
    main()
